export enum AUTH_ROLES {
  KOLACHE_ADMIN = 'KOLACHE_ADMIN',
  KOLACHE_GAME_USER = 'KOLACHE_GAME_USER',
  KOLACHE_BOT_PRODUCTS_WASTE_USER = 'KOLACHE_BOT_PRODUCTS_WASTE_USER',
  // do not use in production
  KOLACHE_TESTING = 'KOLACHE_TESTING',
}
